### ISSUE TITLE
CSS rules 

### ISSUE THREAD

**Issue by bennypowers** [bennypowers/splitjoin.nvim#5]
```css
a { color: blue; font: 12px "Fira Code", monospace; }
```
```css
a {
  color: blue;
  font: 12px "Fira Code", monospace;
}
```
