### ISSUE TITLE
CSS lists

### ISSUE THREAD

**Issue by bennypowers** [bennypowers/splitjoin.nvim#6]
```css
a {
  color: blue;
  font: 12px "Fira Code", monospace;
  /*           ^ cursor */
}
```

```css
a {
  color: blue;
  font:
    12px
    "Fira Code",
    monospace;
}
```
